### ISSUE TITLE
Crash on start.sh

### ISSUE THREAD

**Issue by 1337god** [Pigpog/vlc-discord-rpc#48]
```
├─┬ discord-rpc@3.2.0 
│ ├── UNMET PEER DEPENDENCY bufferutil@^4.0.1
│ ├── node-fetch@2.6.1 
│ ├── UNMET PEER DEPENDENCY utf-8-validate@^5.0.2
│ └── ws@7.4.3 
├── UNMET PEER DEPENDENCY register-scheme@github:devsnek/node-register-scheme
└── vlc.js@3.2.7 


> vlc-discord-rpc@2.2.12 start /home/lain/Programs/vlc-discord-rpc
> node ./src/app.js

/home/lain/Programs/vlc-discord-rpc/node_modules/discord-rpc/src/transports/websocket.js:48
    } catch {} // eslint-disable-line no-empty
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lain/Programs/vlc-discord-rpc/node_modules/discord-rpc/src/transports/index.js:5:14)
```

**Comment by Pigpog** [comment]
This appears to be an issue with the discord-rpc node module. Try deleting the entire node_modules folder and running start.sh again. If that doesn't fix it, I'd assume it's a fault in the module itself

**Comment by 1337god** [comment]
Yeah, it gives the same problem
