### ISSUE TITLE
I'm timed out by the program

### ISSUE THREAD

**Issue by ItsMeSKKYZ3R** [Pigpog/vlc-discord-rpc#71]
**Describe the bug**
The script was timed out
Does the script show an error? Yeah.
```js
Error: RPC_CONNECTION_TIMEOUT
    at Timeout._onTimeout (C:\Users\nicol\Desktop\vlc-discord-rpc\node_modules\discord-rpc\src\client.js:107:47)
```
Does Discord display that you are "Playing VLC Media Player"? Nope

**To Reproduce**
1. Go to 'vlc-discord-rpc'
2. Click on 'start.bat'
3. Scroll down to 'nothing'

**Terminal output**
```js
Starting script...

> vlc-discord-rpc@2.2.12 start
> node ./src/app.js

Connecting to Discord...
An unknown error occurred when connecting to Discord
C:\Users\nicol\Desktop\vlc-discord-rpc\node_modules\discord-rpc\src\client.js:107
      const timeout = setTimeout(() => reject(new Error('RPC_CONNECTION_TIMEOUT')), 10e3);
                                              ^

Error: RPC_CONNECTION_TIMEOUT
    at Timeout._onTimeout (C:\Users\nicol\Desktop\vlc-discord-rpc\node_modules\discord-rpc\src\client.js:107:47)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Your Setup:**
 - OS: Windows
 - NodeJS version: 16.10.0

**Comment by Pigpog** [comment]
Please try restarting Discord or your computer. This is a somewhat common and unexplained issue with Discord's rich presence interface.

**Comment by Pigpog** [comment]
Haven't heard back from you, closing issue
